<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gsprotectedconfig"
 *
 * Auto generated by Extension Builder 2017-03-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'GS Protected Config',
	'description' => 'GS Protected Config allows you to import configurations from outside the web directory or override it dependent from application context or CLI mode. Configuration could simply be adapted by the Extension Manager.',
	'category' => 'misc',
	'author' => 'Simon Gilli',
	'author_email' => 'typo3@gilbertsoft.org',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.9-8.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);